### ISSUE TITLE
Add to operation config an ability to exclude classes when scan packages

### ISSUE THREAD

**Issue by Krasnyanskiy** [Krasnyanskiy/jrsh#132]
I want to set unnecessary classes in the `packages-to-scan`  block to exclude them from available operation list.
```YAML
---
packages-to-scan:
  - com.test.{!DummyOperaion, !TestOperation}
  - org.test.operation.*
classes:
  - com.jaspersoft.jasperserver.jrsh.core.operation.impl.DummyOperation
```
Unlike other classes in the package `com.test.*`, `DummyOperaion` and `TestOperation` classes should be excluded.
