### ISSUE TITLE
As a User I want to exclude/include files from completion via YAML config or programmatically

### ISSUE THREAD

**Issue by Krasnyanskiy** [Krasnyanskiy/jrsh#6]
When we navigate through FS we usually get a folder with enormous bunch of files. And displaying this content is actually an inconvenient task. Instead of seeing all those files I want to limit them or, even better, to filter them by a short bunch of types. For example, I want to see only `zip` and `jrxml` files.

So it's nice to have some filtering mechanism to exclude files (e.g. by mask) from completion.
#### Config example

``` yaml

---
file_filter:
    include:
      - zip
      - jrxml
```

or

``` yaml

---
file_filter:
    exclude:
      - jpeg
      - .* (any hidden)
```
#### And programmatically

``` bash
$ import --filter "zip" "jrxml" from /Users/alex/folder/file.zip
```
