### ISSUE TITLE
As User I can set default profile (persisted)

### ISSUE THREAD

**Issue by Krasnyanskiy** [Krasnyanskiy/jrsh#66]
## Acceptance criteria
1. The command below should set profile as default in the configuration file.
```bash
>>> profile default "JRS_DEFAULT"
```
2. Profile configuration file should have a default profile as root field.

#### Possible format
```YAML
# Do not attempt to modify the file manually. All changes should be done 
# programmatically. In the case of manual modification of this file, 
# the correct performance of the application just cannot be guaranteed.

---
profiles:
  - default:
     name: JRS_DEFAULT
     organization: organization_1
     url: 'http://localhost:8080/jasperserver-pro'
     username: superuser

  - name: JRS_1
    organization: organization_1
    url: 'http://localhost:8080/jasperserver-pro'
    username: superuser

  - name: JRS_2
    url: 'http://54.221.179.184/jasperserver-pro'
    username: jasperadmin
```

3. We also need to have a comment in `profiles.yml` which warns the user about profile modification.

```YAML
# Do not attempt to modify the file manually. All changes should be done 
# programmatically. In the case of manual modification of this file, 
# the correct performance of the application just cannot be guaranteed.
```

**Comment by Krasnyanskiy** [comment]
### Here is new format of file
```yaml
# ==========================================================================
# === Do not attempt to modify this file manually. All changes should be ===
# === done programmatically. In the case of manual modification, the     ===
# === correct performance of the application just cannot be guaranteed.  ===
# ==========================================================================
---
default: AWS-CLOUD-JRS
profiles:
  - name: AWS-CLOUD-JRS
    url: http://54.167.46.45/jasperserver-pro
    username: hans

  - name: JRS-LOCAL-2
    url: http://localhost:8085/jasperserver-pro
    username: dietrich

  - name: JRS-LOCAL-3
    url: http://localhost:8081/jasperserver-pro
    username: klaus

  - name: JRS-LOCAL-4
    url: http://localhost:8082/jasperserver-pro
    username: adolfych
```
