### ISSUE TITLE
As User I cannot create duplicate profiles with the same name

### ISSUE THREAD

**Issue by Krasnyanskiy** [Krasnyanskiy/jrsh#70]
## Acceptance criteria
We cannot save the same profile twice.
```bash
>>> profile save "JRS-4"
>>> profile save "JRS-4"
```
And it is not allowed to include several profiles with the same name into the configuration file `profiles.yml`  :no_entry_sign: 
```YAML
profiles:
- {
    name: JRS-8,
    url: 'http://54.90.191.114/jasperserver-pro',
    username: superuser
  }
- {
    name: JRS-8,
    url: 'http://172.28.146.32:8080/jasperserver-pro',
    username: superuser,
    organization: organization_1
  }
```
